version: '3.6'

services:

  node:
    restart: always
    build:
      context: ./services/node
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - mysql

  nginx:
    restart: always
    build:
      context: ./services/frontend
    volumes:
      - './services/frontend:/usr/share/nginx/html'
    ports:
     - 8080:80
    depends_on:
      - node

  mysql:
    image: mysql:8
    # Allows version 8+ to run with username/pass for auth
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Options for MySQL setup. This config creates a db with no password for the root user
      # MYSQL_ROOT_PASSWORD: banana
      # MYSQL_USER: root
      # MYSQL_PASSWORD: pass
      # MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: value
      MYSQL_DATABASE: my_db
    # This places our schema file inside the container and runs the schema file when the db starts
    volumes:
      - './services/db/schema:/docker-entrypoint-initdb.d'
# this will persist data to disk:
      # - './services/db/data:/var/lib/mysql'
